### ISSUE TITLE
Bad OpenGApps image

### ISSUE THREAD

**Issue by jusabatier** [vinnyfs89/ragnarok-m-on-linux#1]
It looks like the OpenGApps screen is not the right one.

**Comment by vinnyfs89** [comment]
@jusabatier  Which one?

**Comment by jusabatier** [comment]
Under : 

> Access OpenGApps and select the options below and click Download button

The screenshot doesn't show any OpenGApps option...

**Comment by vinnyfs89** [comment]
Done. Thanks!
